spring.application.name=publisher
server.port=8081
rabbitmq.queuename=MY_TEST_QUEUE

rabbitmq.host=${RABBIT_HOST}
rabbitmq.username=${RABBIT_USERNAME}
rabbitmq.password=${RABBIT_PASSWORD}
rabbitmq.port=${RABBIT_PORT}